// Code generated by go-swagger; DO NOT EDIT.

package test

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new test API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for test API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientService is the interface for Client methods
type ClientService interface {
	TestRead(params *TestReadParams, authInfo runtime.ClientAuthInfoWriter) (*TestReadOK, error)

	TestWrite(params *TestWriteParams, authInfo runtime.ClientAuthInfoWriter) (*TestWriteOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  TestRead reads test

  A read-only endpoint for testing your authentication key.
*/
func (a *Client) TestRead(params *TestReadParams, authInfo runtime.ClientAuthInfoWriter) (*TestReadOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewTestReadParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "testRead",
		Method:             "GET",
		PathPattern:        "/{organization}/test",
		ProducesMediaTypes: []string{"application/text"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &TestReadReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*TestReadOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for testRead: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  TestWrite writes test

  A write endpoint for testing your authentication key.
*/
func (a *Client) TestWrite(params *TestWriteParams, authInfo runtime.ClientAuthInfoWriter) (*TestWriteOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewTestWriteParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "testWrite",
		Method:             "POST",
		PathPattern:        "/{organization}/test",
		ProducesMediaTypes: []string{"application/text"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &TestWriteReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*TestWriteOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for testWrite: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
