// Code generated by go-swagger; DO NOT EDIT.

package traces

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewStoredTracesIDParams creates a new StoredTracesIDParams object
// with the default values initialized.
func NewStoredTracesIDParams() *StoredTracesIDParams {
	var ()
	return &StoredTracesIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewStoredTracesIDParamsWithTimeout creates a new StoredTracesIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewStoredTracesIDParamsWithTimeout(timeout time.Duration) *StoredTracesIDParams {
	var ()
	return &StoredTracesIDParams{

		timeout: timeout,
	}
}

// NewStoredTracesIDParamsWithContext creates a new StoredTracesIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewStoredTracesIDParamsWithContext(ctx context.Context) *StoredTracesIDParams {
	var ()
	return &StoredTracesIDParams{

		Context: ctx,
	}
}

// NewStoredTracesIDParamsWithHTTPClient creates a new StoredTracesIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewStoredTracesIDParamsWithHTTPClient(client *http.Client) *StoredTracesIDParams {
	var ()
	return &StoredTracesIDParams{
		HTTPClient: client,
	}
}

/*StoredTracesIDParams contains all the parameters to send to the API endpoint
for the stored traces ID operation typically these are written to a http.Request
*/
type StoredTracesIDParams struct {

	/*Organization
	  Name of the customer organization

	*/
	Organization string
	/*Project
	  Name of the project that the trace belongs to

	*/
	Project string
	/*SpanID
	  Key that uniquely identifies a stored trace

	*/
	SpanID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the stored traces ID params
func (o *StoredTracesIDParams) WithTimeout(timeout time.Duration) *StoredTracesIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the stored traces ID params
func (o *StoredTracesIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the stored traces ID params
func (o *StoredTracesIDParams) WithContext(ctx context.Context) *StoredTracesIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the stored traces ID params
func (o *StoredTracesIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the stored traces ID params
func (o *StoredTracesIDParams) WithHTTPClient(client *http.Client) *StoredTracesIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the stored traces ID params
func (o *StoredTracesIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOrganization adds the organization to the stored traces ID params
func (o *StoredTracesIDParams) WithOrganization(organization string) *StoredTracesIDParams {
	o.SetOrganization(organization)
	return o
}

// SetOrganization adds the organization to the stored traces ID params
func (o *StoredTracesIDParams) SetOrganization(organization string) {
	o.Organization = organization
}

// WithProject adds the project to the stored traces ID params
func (o *StoredTracesIDParams) WithProject(project string) *StoredTracesIDParams {
	o.SetProject(project)
	return o
}

// SetProject adds the project to the stored traces ID params
func (o *StoredTracesIDParams) SetProject(project string) {
	o.Project = project
}

// WithSpanID adds the spanID to the stored traces ID params
func (o *StoredTracesIDParams) WithSpanID(spanID string) *StoredTracesIDParams {
	o.SetSpanID(spanID)
	return o
}

// SetSpanID adds the spanId to the stored traces ID params
func (o *StoredTracesIDParams) SetSpanID(spanID string) {
	o.SpanID = spanID
}

// WriteToRequest writes these params to a swagger request
func (o *StoredTracesIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param organization
	if err := r.SetPathParam("organization", o.Organization); err != nil {
		return err
	}

	// path param project
	if err := r.SetPathParam("project", o.Project); err != nil {
		return err
	}

	// query param span-id
	qrSpanID := o.SpanID
	qSpanID := qrSpanID
	if qSpanID != "" {
		if err := r.SetQueryParam("span-id", qSpanID); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
