// Code generated by go-swagger; DO NOT EDIT.

package workflow_links

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteWorkflowLinkParams creates a new DeleteWorkflowLinkParams object
// with the default values initialized.
func NewDeleteWorkflowLinkParams() *DeleteWorkflowLinkParams {
	var ()
	return &DeleteWorkflowLinkParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteWorkflowLinkParamsWithTimeout creates a new DeleteWorkflowLinkParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteWorkflowLinkParamsWithTimeout(timeout time.Duration) *DeleteWorkflowLinkParams {
	var ()
	return &DeleteWorkflowLinkParams{

		timeout: timeout,
	}
}

// NewDeleteWorkflowLinkParamsWithContext creates a new DeleteWorkflowLinkParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteWorkflowLinkParamsWithContext(ctx context.Context) *DeleteWorkflowLinkParams {
	var ()
	return &DeleteWorkflowLinkParams{

		Context: ctx,
	}
}

// NewDeleteWorkflowLinkParamsWithHTTPClient creates a new DeleteWorkflowLinkParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteWorkflowLinkParamsWithHTTPClient(client *http.Client) *DeleteWorkflowLinkParams {
	var ()
	return &DeleteWorkflowLinkParams{
		HTTPClient: client,
	}
}

/*DeleteWorkflowLinkParams contains all the parameters to send to the API endpoint
for the delete workflow link operation typically these are written to a http.Request
*/
type DeleteWorkflowLinkParams struct {

	/*LinkID
	  Identifier of the workflow link to delete

	*/
	LinkID string
	/*Organization
	  Name of the customer organization

	*/
	Organization string
	/*Project
	  Name of the customer project

	*/
	Project string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete workflow link params
func (o *DeleteWorkflowLinkParams) WithTimeout(timeout time.Duration) *DeleteWorkflowLinkParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete workflow link params
func (o *DeleteWorkflowLinkParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete workflow link params
func (o *DeleteWorkflowLinkParams) WithContext(ctx context.Context) *DeleteWorkflowLinkParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete workflow link params
func (o *DeleteWorkflowLinkParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete workflow link params
func (o *DeleteWorkflowLinkParams) WithHTTPClient(client *http.Client) *DeleteWorkflowLinkParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete workflow link params
func (o *DeleteWorkflowLinkParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithLinkID adds the linkID to the delete workflow link params
func (o *DeleteWorkflowLinkParams) WithLinkID(linkID string) *DeleteWorkflowLinkParams {
	o.SetLinkID(linkID)
	return o
}

// SetLinkID adds the linkId to the delete workflow link params
func (o *DeleteWorkflowLinkParams) SetLinkID(linkID string) {
	o.LinkID = linkID
}

// WithOrganization adds the organization to the delete workflow link params
func (o *DeleteWorkflowLinkParams) WithOrganization(organization string) *DeleteWorkflowLinkParams {
	o.SetOrganization(organization)
	return o
}

// SetOrganization adds the organization to the delete workflow link params
func (o *DeleteWorkflowLinkParams) SetOrganization(organization string) {
	o.Organization = organization
}

// WithProject adds the project to the delete workflow link params
func (o *DeleteWorkflowLinkParams) WithProject(project string) *DeleteWorkflowLinkParams {
	o.SetProject(project)
	return o
}

// SetProject adds the project to the delete workflow link params
func (o *DeleteWorkflowLinkParams) SetProject(project string) {
	o.Project = project
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteWorkflowLinkParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param link-id
	if err := r.SetPathParam("link-id", o.LinkID); err != nil {
		return err
	}

	// path param organization
	if err := r.SetPathParam("organization", o.Organization); err != nil {
		return err
	}

	// path param project
	if err := r.SetPathParam("project", o.Project); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
