// Code generated by go-swagger; DO NOT EDIT.

package workflow_links

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DeleteWorkflowLinkIDReader is a Reader for the DeleteWorkflowLinkID structure.
type DeleteWorkflowLinkIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteWorkflowLinkIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteWorkflowLinkIDNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewDeleteWorkflowLinkIDUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteWorkflowLinkIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteWorkflowLinkIDNoContent creates a DeleteWorkflowLinkIDNoContent with default headers values
func NewDeleteWorkflowLinkIDNoContent() *DeleteWorkflowLinkIDNoContent {
	return &DeleteWorkflowLinkIDNoContent{}
}

/*DeleteWorkflowLinkIDNoContent handles this case with default header values.

The workflow link was successfully deleted
*/
type DeleteWorkflowLinkIDNoContent struct {
}

func (o *DeleteWorkflowLinkIDNoContent) Error() string {
	return fmt.Sprintf("[DELETE /{organization}/projects/{project}/wf_links/{link-id}][%d] deleteWorkflowLinkIdNoContent ", 204)
}

func (o *DeleteWorkflowLinkIDNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteWorkflowLinkIDUnauthorized creates a DeleteWorkflowLinkIDUnauthorized with default headers values
func NewDeleteWorkflowLinkIDUnauthorized() *DeleteWorkflowLinkIDUnauthorized {
	return &DeleteWorkflowLinkIDUnauthorized{}
}

/*DeleteWorkflowLinkIDUnauthorized handles this case with default header values.

The API Key does not provide access to this resource
*/
type DeleteWorkflowLinkIDUnauthorized struct {
}

func (o *DeleteWorkflowLinkIDUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /{organization}/projects/{project}/wf_links/{link-id}][%d] deleteWorkflowLinkIdUnauthorized ", 401)
}

func (o *DeleteWorkflowLinkIDUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteWorkflowLinkIDNotFound creates a DeleteWorkflowLinkIDNotFound with default headers values
func NewDeleteWorkflowLinkIDNotFound() *DeleteWorkflowLinkIDNotFound {
	return &DeleteWorkflowLinkIDNotFound{}
}

/*DeleteWorkflowLinkIDNotFound handles this case with default header values.

Organization, project name, or workflow link ID is not found
*/
type DeleteWorkflowLinkIDNotFound struct {
}

func (o *DeleteWorkflowLinkIDNotFound) Error() string {
	return fmt.Sprintf("[DELETE /{organization}/projects/{project}/wf_links/{link-id}][%d] deleteWorkflowLinkIdNotFound ", 404)
}

func (o *DeleteWorkflowLinkIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
