// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
)

// Micros micros
// swagger:model Micros
type Micros int64

// Validate validates this micros
func (m Micros) Validate(formats strfmt.Registry) error {
	return nil
}
