// Code generated by go-swagger; DO NOT EDIT.

package conditions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewListConditionsForStreamParams creates a new ListConditionsForStreamParams object
// with the default values initialized.
func NewListConditionsForStreamParams() *ListConditionsForStreamParams {
	var ()
	return &ListConditionsForStreamParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewListConditionsForStreamParamsWithTimeout creates a new ListConditionsForStreamParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListConditionsForStreamParamsWithTimeout(timeout time.Duration) *ListConditionsForStreamParams {
	var ()
	return &ListConditionsForStreamParams{

		timeout: timeout,
	}
}

// NewListConditionsForStreamParamsWithContext creates a new ListConditionsForStreamParams object
// with the default values initialized, and the ability to set a context for a request
func NewListConditionsForStreamParamsWithContext(ctx context.Context) *ListConditionsForStreamParams {
	var ()
	return &ListConditionsForStreamParams{

		Context: ctx,
	}
}

// NewListConditionsForStreamParamsWithHTTPClient creates a new ListConditionsForStreamParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewListConditionsForStreamParamsWithHTTPClient(client *http.Client) *ListConditionsForStreamParams {
	var ()
	return &ListConditionsForStreamParams{
		HTTPClient: client,
	}
}

/*ListConditionsForStreamParams contains all the parameters to send to the API endpoint
for the list conditions for stream operation typically these are written to a http.Request
*/
type ListConditionsForStreamParams struct {

	/*Organization
	  Name of the customer organization

	*/
	Organization string
	/*Project
	  Name of the customer project

	*/
	Project string
	/*StreamID
	  Stream identifier

	*/
	StreamID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list conditions for stream params
func (o *ListConditionsForStreamParams) WithTimeout(timeout time.Duration) *ListConditionsForStreamParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list conditions for stream params
func (o *ListConditionsForStreamParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list conditions for stream params
func (o *ListConditionsForStreamParams) WithContext(ctx context.Context) *ListConditionsForStreamParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list conditions for stream params
func (o *ListConditionsForStreamParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list conditions for stream params
func (o *ListConditionsForStreamParams) WithHTTPClient(client *http.Client) *ListConditionsForStreamParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list conditions for stream params
func (o *ListConditionsForStreamParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOrganization adds the organization to the list conditions for stream params
func (o *ListConditionsForStreamParams) WithOrganization(organization string) *ListConditionsForStreamParams {
	o.SetOrganization(organization)
	return o
}

// SetOrganization adds the organization to the list conditions for stream params
func (o *ListConditionsForStreamParams) SetOrganization(organization string) {
	o.Organization = organization
}

// WithProject adds the project to the list conditions for stream params
func (o *ListConditionsForStreamParams) WithProject(project string) *ListConditionsForStreamParams {
	o.SetProject(project)
	return o
}

// SetProject adds the project to the list conditions for stream params
func (o *ListConditionsForStreamParams) SetProject(project string) {
	o.Project = project
}

// WithStreamID adds the streamID to the list conditions for stream params
func (o *ListConditionsForStreamParams) WithStreamID(streamID string) *ListConditionsForStreamParams {
	o.SetStreamID(streamID)
	return o
}

// SetStreamID adds the streamId to the list conditions for stream params
func (o *ListConditionsForStreamParams) SetStreamID(streamID string) {
	o.StreamID = streamID
}

// WriteToRequest writes these params to a swagger request
func (o *ListConditionsForStreamParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param organization
	if err := r.SetPathParam("organization", o.Organization); err != nil {
		return err
	}

	// path param project
	if err := r.SetPathParam("project", o.Project); err != nil {
		return err
	}

	// path param stream-id
	if err := r.SetPathParam("stream-id", o.StreamID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
