// Code generated by go-swagger; DO NOT EDIT.

package conditions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewListConditionsForStreamIDParams creates a new ListConditionsForStreamIDParams object
// with the default values initialized.
func NewListConditionsForStreamIDParams() *ListConditionsForStreamIDParams {
	var ()
	return &ListConditionsForStreamIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewListConditionsForStreamIDParamsWithTimeout creates a new ListConditionsForStreamIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListConditionsForStreamIDParamsWithTimeout(timeout time.Duration) *ListConditionsForStreamIDParams {
	var ()
	return &ListConditionsForStreamIDParams{

		timeout: timeout,
	}
}

// NewListConditionsForStreamIDParamsWithContext creates a new ListConditionsForStreamIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewListConditionsForStreamIDParamsWithContext(ctx context.Context) *ListConditionsForStreamIDParams {
	var ()
	return &ListConditionsForStreamIDParams{

		Context: ctx,
	}
}

// NewListConditionsForStreamIDParamsWithHTTPClient creates a new ListConditionsForStreamIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewListConditionsForStreamIDParamsWithHTTPClient(client *http.Client) *ListConditionsForStreamIDParams {
	var ()
	return &ListConditionsForStreamIDParams{
		HTTPClient: client,
	}
}

/*ListConditionsForStreamIDParams contains all the parameters to send to the API endpoint
for the list conditions for stream ID operation typically these are written to a http.Request
*/
type ListConditionsForStreamIDParams struct {

	/*Organization
	  Name of the customer organization

	*/
	Organization string
	/*Project
	  Name of the customer project

	*/
	Project string
	/*StreamID
	  Stream identifier

	*/
	StreamID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list conditions for stream ID params
func (o *ListConditionsForStreamIDParams) WithTimeout(timeout time.Duration) *ListConditionsForStreamIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list conditions for stream ID params
func (o *ListConditionsForStreamIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list conditions for stream ID params
func (o *ListConditionsForStreamIDParams) WithContext(ctx context.Context) *ListConditionsForStreamIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list conditions for stream ID params
func (o *ListConditionsForStreamIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list conditions for stream ID params
func (o *ListConditionsForStreamIDParams) WithHTTPClient(client *http.Client) *ListConditionsForStreamIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list conditions for stream ID params
func (o *ListConditionsForStreamIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOrganization adds the organization to the list conditions for stream ID params
func (o *ListConditionsForStreamIDParams) WithOrganization(organization string) *ListConditionsForStreamIDParams {
	o.SetOrganization(organization)
	return o
}

// SetOrganization adds the organization to the list conditions for stream ID params
func (o *ListConditionsForStreamIDParams) SetOrganization(organization string) {
	o.Organization = organization
}

// WithProject adds the project to the list conditions for stream ID params
func (o *ListConditionsForStreamIDParams) WithProject(project string) *ListConditionsForStreamIDParams {
	o.SetProject(project)
	return o
}

// SetProject adds the project to the list conditions for stream ID params
func (o *ListConditionsForStreamIDParams) SetProject(project string) {
	o.Project = project
}

// WithStreamID adds the streamID to the list conditions for stream ID params
func (o *ListConditionsForStreamIDParams) WithStreamID(streamID string) *ListConditionsForStreamIDParams {
	o.SetStreamID(streamID)
	return o
}

// SetStreamID adds the streamId to the list conditions for stream ID params
func (o *ListConditionsForStreamIDParams) SetStreamID(streamID string) {
	o.StreamID = streamID
}

// WriteToRequest writes these params to a swagger request
func (o *ListConditionsForStreamIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param organization
	if err := r.SetPathParam("organization", o.Organization); err != nil {
		return err
	}

	// path param project
	if err := r.SetPathParam("project", o.Project); err != nil {
		return err
	}

	// path param stream-id
	if err := r.SetPathParam("stream-id", o.StreamID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
