// Code generated by go-swagger; DO NOT EDIT.

package conditions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/ledor473/lightstep-api-go/v0.1/models"
)

// NewPatchConditionIDParams creates a new PatchConditionIDParams object
// with the default values initialized.
func NewPatchConditionIDParams() *PatchConditionIDParams {
	var ()
	return &PatchConditionIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPatchConditionIDParamsWithTimeout creates a new PatchConditionIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPatchConditionIDParamsWithTimeout(timeout time.Duration) *PatchConditionIDParams {
	var ()
	return &PatchConditionIDParams{

		timeout: timeout,
	}
}

// NewPatchConditionIDParamsWithContext creates a new PatchConditionIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewPatchConditionIDParamsWithContext(ctx context.Context) *PatchConditionIDParams {
	var ()
	return &PatchConditionIDParams{

		Context: ctx,
	}
}

// NewPatchConditionIDParamsWithHTTPClient creates a new PatchConditionIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPatchConditionIDParamsWithHTTPClient(client *http.Client) *PatchConditionIDParams {
	var ()
	return &PatchConditionIDParams{
		HTTPClient: client,
	}
}

/*PatchConditionIDParams contains all the parameters to send to the API endpoint
for the patch condition ID operation typically these are written to a http.Request
*/
type PatchConditionIDParams struct {

	/*ConditionID
	  Identifier of the condition to modify

	*/
	ConditionID string
	/*Data
	  Condition definition

	*/
	Data *models.ConditionRequestBody
	/*Organization
	  Name of the customer organization

	*/
	Organization string
	/*Project
	  Name of the customer project

	*/
	Project string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the patch condition ID params
func (o *PatchConditionIDParams) WithTimeout(timeout time.Duration) *PatchConditionIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the patch condition ID params
func (o *PatchConditionIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the patch condition ID params
func (o *PatchConditionIDParams) WithContext(ctx context.Context) *PatchConditionIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the patch condition ID params
func (o *PatchConditionIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the patch condition ID params
func (o *PatchConditionIDParams) WithHTTPClient(client *http.Client) *PatchConditionIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the patch condition ID params
func (o *PatchConditionIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithConditionID adds the conditionID to the patch condition ID params
func (o *PatchConditionIDParams) WithConditionID(conditionID string) *PatchConditionIDParams {
	o.SetConditionID(conditionID)
	return o
}

// SetConditionID adds the conditionId to the patch condition ID params
func (o *PatchConditionIDParams) SetConditionID(conditionID string) {
	o.ConditionID = conditionID
}

// WithData adds the data to the patch condition ID params
func (o *PatchConditionIDParams) WithData(data *models.ConditionRequestBody) *PatchConditionIDParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the patch condition ID params
func (o *PatchConditionIDParams) SetData(data *models.ConditionRequestBody) {
	o.Data = data
}

// WithOrganization adds the organization to the patch condition ID params
func (o *PatchConditionIDParams) WithOrganization(organization string) *PatchConditionIDParams {
	o.SetOrganization(organization)
	return o
}

// SetOrganization adds the organization to the patch condition ID params
func (o *PatchConditionIDParams) SetOrganization(organization string) {
	o.Organization = organization
}

// WithProject adds the project to the patch condition ID params
func (o *PatchConditionIDParams) WithProject(project string) *PatchConditionIDParams {
	o.SetProject(project)
	return o
}

// SetProject adds the project to the patch condition ID params
func (o *PatchConditionIDParams) SetProject(project string) {
	o.Project = project
}

// WriteToRequest writes these params to a swagger request
func (o *PatchConditionIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param condition-id
	if err := r.SetPathParam("condition-id", o.ConditionID); err != nil {
		return err
	}

	if o.Data != nil {
		if err := r.SetBodyParam(o.Data); err != nil {
			return err
		}
	}

	// path param organization
	if err := r.SetPathParam("organization", o.Organization); err != nil {
		return err
	}

	// path param project
	if err := r.SetPathParam("project", o.Project); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
