// Code generated by go-swagger; DO NOT EDIT.

package workflow_links

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetWorkflowLinkParams creates a new GetWorkflowLinkParams object
// with the default values initialized.
func NewGetWorkflowLinkParams() *GetWorkflowLinkParams {
	var ()
	return &GetWorkflowLinkParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetWorkflowLinkParamsWithTimeout creates a new GetWorkflowLinkParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetWorkflowLinkParamsWithTimeout(timeout time.Duration) *GetWorkflowLinkParams {
	var ()
	return &GetWorkflowLinkParams{

		timeout: timeout,
	}
}

// NewGetWorkflowLinkParamsWithContext creates a new GetWorkflowLinkParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetWorkflowLinkParamsWithContext(ctx context.Context) *GetWorkflowLinkParams {
	var ()
	return &GetWorkflowLinkParams{

		Context: ctx,
	}
}

// NewGetWorkflowLinkParamsWithHTTPClient creates a new GetWorkflowLinkParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetWorkflowLinkParamsWithHTTPClient(client *http.Client) *GetWorkflowLinkParams {
	var ()
	return &GetWorkflowLinkParams{
		HTTPClient: client,
	}
}

/*GetWorkflowLinkParams contains all the parameters to send to the API endpoint
for the get workflow link operation typically these are written to a http.Request
*/
type GetWorkflowLinkParams struct {

	/*LinkID
	  Workflow Link identifier

	*/
	LinkID string
	/*Organization
	  Name of the customer organization

	*/
	Organization string
	/*Project
	  Name of the customer project

	*/
	Project string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get workflow link params
func (o *GetWorkflowLinkParams) WithTimeout(timeout time.Duration) *GetWorkflowLinkParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get workflow link params
func (o *GetWorkflowLinkParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get workflow link params
func (o *GetWorkflowLinkParams) WithContext(ctx context.Context) *GetWorkflowLinkParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get workflow link params
func (o *GetWorkflowLinkParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get workflow link params
func (o *GetWorkflowLinkParams) WithHTTPClient(client *http.Client) *GetWorkflowLinkParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get workflow link params
func (o *GetWorkflowLinkParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithLinkID adds the linkID to the get workflow link params
func (o *GetWorkflowLinkParams) WithLinkID(linkID string) *GetWorkflowLinkParams {
	o.SetLinkID(linkID)
	return o
}

// SetLinkID adds the linkId to the get workflow link params
func (o *GetWorkflowLinkParams) SetLinkID(linkID string) {
	o.LinkID = linkID
}

// WithOrganization adds the organization to the get workflow link params
func (o *GetWorkflowLinkParams) WithOrganization(organization string) *GetWorkflowLinkParams {
	o.SetOrganization(organization)
	return o
}

// SetOrganization adds the organization to the get workflow link params
func (o *GetWorkflowLinkParams) SetOrganization(organization string) {
	o.Organization = organization
}

// WithProject adds the project to the get workflow link params
func (o *GetWorkflowLinkParams) WithProject(project string) *GetWorkflowLinkParams {
	o.SetProject(project)
	return o
}

// SetProject adds the project to the get workflow link params
func (o *GetWorkflowLinkParams) SetProject(project string) {
	o.Project = project
}

// WriteToRequest writes these params to a swagger request
func (o *GetWorkflowLinkParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param link-id
	if err := r.SetPathParam("link-id", o.LinkID); err != nil {
		return err
	}

	// path param organization
	if err := r.SetPathParam("organization", o.Organization); err != nil {
		return err
	}

	// path param project
	if err := r.SetPathParam("project", o.Project); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
