// Code generated by go-swagger; DO NOT EDIT.

package traces

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

//go:generate mockery -name API -inpkg

// API is the interface of the traces client
type API interface {
	/*
	   StoredTraces storeds traces

	   Returns complete traces that have already been assembled and stored. You must include a [span-id](https://docs.lightstep.com/docs/spans-in-opentelemetry) as a query parameter.*/
	StoredTraces(ctx context.Context, params *StoredTracesParams) (*StoredTracesOK, error)
}

// New creates a new traces API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry, authInfo runtime.ClientAuthInfoWriter) *Client {
	return &Client{
		transport: transport,
		formats:   formats,
		authInfo:  authInfo,
	}
}

/*
Client for traces API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
	authInfo  runtime.ClientAuthInfoWriter
}

/*
StoredTraces storeds traces

Returns complete traces that have already been assembled and stored. You must include a [span-id](https://docs.lightstep.com/docs/spans-in-opentelemetry) as a query parameter.
*/
func (a *Client) StoredTraces(ctx context.Context, params *StoredTracesParams) (*StoredTracesOK, error) {

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "storedTraces",
		Method:             "GET",
		PathPattern:        "/{organization}/projects/{project}/stored-traces",
		ProducesMediaTypes: []string{"application/json", "application/vnd.api+json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &StoredTracesReader{formats: a.formats},
		AuthInfo:           a.authInfo,
		Context:            ctx,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*StoredTracesOK), nil

}
