// Code generated by go-swagger; DO NOT EDIT.

package conditions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteConditionReader is a Reader for the DeleteCondition structure.
type DeleteConditionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteConditionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteConditionNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewDeleteConditionUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteConditionNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteConditionNoContent creates a DeleteConditionNoContent with default headers values
func NewDeleteConditionNoContent() *DeleteConditionNoContent {
	return &DeleteConditionNoContent{}
}

/*DeleteConditionNoContent handles this case with default header values.

Condition was successfully deleted
*/
type DeleteConditionNoContent struct {
}

func (o *DeleteConditionNoContent) Error() string {
	return fmt.Sprintf("[DELETE /{organization}/projects/{project}/conditions/{condition-id}][%d] deleteConditionNoContent ", 204)
}

func (o *DeleteConditionNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteConditionUnauthorized creates a DeleteConditionUnauthorized with default headers values
func NewDeleteConditionUnauthorized() *DeleteConditionUnauthorized {
	return &DeleteConditionUnauthorized{}
}

/*DeleteConditionUnauthorized handles this case with default header values.

The API Key does not provide access to this resource, or the organization name does not exist
*/
type DeleteConditionUnauthorized struct {
}

func (o *DeleteConditionUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /{organization}/projects/{project}/conditions/{condition-id}][%d] deleteConditionUnauthorized ", 401)
}

func (o *DeleteConditionUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteConditionNotFound creates a DeleteConditionNotFound with default headers values
func NewDeleteConditionNotFound() *DeleteConditionNotFound {
	return &DeleteConditionNotFound{}
}

/*DeleteConditionNotFound handles this case with default header values.

Project name is not found
*/
type DeleteConditionNotFound struct {
}

func (o *DeleteConditionNotFound) Error() string {
	return fmt.Sprintf("[DELETE /{organization}/projects/{project}/conditions/{condition-id}][%d] deleteConditionNotFound ", 404)
}

func (o *DeleteConditionNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
