// Code generated by go-swagger; DO NOT EDIT.

package conditions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetConditionParams creates a new GetConditionParams object
// with the default values initialized.
func NewGetConditionParams() *GetConditionParams {
	var ()
	return &GetConditionParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetConditionParamsWithTimeout creates a new GetConditionParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetConditionParamsWithTimeout(timeout time.Duration) *GetConditionParams {
	var ()
	return &GetConditionParams{

		timeout: timeout,
	}
}

// NewGetConditionParamsWithContext creates a new GetConditionParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetConditionParamsWithContext(ctx context.Context) *GetConditionParams {
	var ()
	return &GetConditionParams{

		Context: ctx,
	}
}

// NewGetConditionParamsWithHTTPClient creates a new GetConditionParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetConditionParamsWithHTTPClient(client *http.Client) *GetConditionParams {
	var ()
	return &GetConditionParams{
		HTTPClient: client,
	}
}

/*GetConditionParams contains all the parameters to send to the API endpoint
for the get condition operation typically these are written to a http.Request
*/
type GetConditionParams struct {

	/*ConditionID
	  Condition identifier

	*/
	ConditionID string
	/*Organization
	  Name of the customer organization

	*/
	Organization string
	/*Project
	  Name of the customer project

	*/
	Project string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get condition params
func (o *GetConditionParams) WithTimeout(timeout time.Duration) *GetConditionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get condition params
func (o *GetConditionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get condition params
func (o *GetConditionParams) WithContext(ctx context.Context) *GetConditionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get condition params
func (o *GetConditionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get condition params
func (o *GetConditionParams) WithHTTPClient(client *http.Client) *GetConditionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get condition params
func (o *GetConditionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithConditionID adds the conditionID to the get condition params
func (o *GetConditionParams) WithConditionID(conditionID string) *GetConditionParams {
	o.SetConditionID(conditionID)
	return o
}

// SetConditionID adds the conditionId to the get condition params
func (o *GetConditionParams) SetConditionID(conditionID string) {
	o.ConditionID = conditionID
}

// WithOrganization adds the organization to the get condition params
func (o *GetConditionParams) WithOrganization(organization string) *GetConditionParams {
	o.SetOrganization(organization)
	return o
}

// SetOrganization adds the organization to the get condition params
func (o *GetConditionParams) SetOrganization(organization string) {
	o.Organization = organization
}

// WithProject adds the project to the get condition params
func (o *GetConditionParams) WithProject(project string) *GetConditionParams {
	o.SetProject(project)
	return o
}

// SetProject adds the project to the get condition params
func (o *GetConditionParams) SetProject(project string) {
	o.Project = project
}

// WriteToRequest writes these params to a swagger request
func (o *GetConditionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param condition-id
	if err := r.SetPathParam("condition-id", o.ConditionID); err != nil {
		return err
	}

	// path param organization
	if err := r.SetPathParam("organization", o.Organization); err != nil {
		return err
	}

	// path param project
	if err := r.SetPathParam("project", o.Project); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
