// Code generated by go-swagger; DO NOT EDIT.

package test

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewTestReadParams creates a new TestReadParams object
// with the default values initialized.
func NewTestReadParams() *TestReadParams {
	var ()
	return &TestReadParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewTestReadParamsWithTimeout creates a new TestReadParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewTestReadParamsWithTimeout(timeout time.Duration) *TestReadParams {
	var ()
	return &TestReadParams{

		timeout: timeout,
	}
}

// NewTestReadParamsWithContext creates a new TestReadParams object
// with the default values initialized, and the ability to set a context for a request
func NewTestReadParamsWithContext(ctx context.Context) *TestReadParams {
	var ()
	return &TestReadParams{

		Context: ctx,
	}
}

// NewTestReadParamsWithHTTPClient creates a new TestReadParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewTestReadParamsWithHTTPClient(client *http.Client) *TestReadParams {
	var ()
	return &TestReadParams{
		HTTPClient: client,
	}
}

/*TestReadParams contains all the parameters to send to the API endpoint
for the test read operation typically these are written to a http.Request
*/
type TestReadParams struct {

	/*Organization
	  Name of the customer organization

	*/
	Organization string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the test read params
func (o *TestReadParams) WithTimeout(timeout time.Duration) *TestReadParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the test read params
func (o *TestReadParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the test read params
func (o *TestReadParams) WithContext(ctx context.Context) *TestReadParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the test read params
func (o *TestReadParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the test read params
func (o *TestReadParams) WithHTTPClient(client *http.Client) *TestReadParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the test read params
func (o *TestReadParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOrganization adds the organization to the test read params
func (o *TestReadParams) WithOrganization(organization string) *TestReadParams {
	o.SetOrganization(organization)
	return o
}

// SetOrganization adds the organization to the test read params
func (o *TestReadParams) SetOrganization(organization string) {
	o.Organization = organization
}

// WriteToRequest writes these params to a swagger request
func (o *TestReadParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param organization
	if err := r.SetPathParam("organization", o.Organization); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
