// Code generated by go-swagger; DO NOT EDIT.

package client

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	httptransport "github.com/go-openapi/runtime/client"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ledor473/lightstep-api-go/pkg/v0.1/client/conditions"
	"github.com/ledor473/lightstep-api-go/pkg/v0.1/client/dashboards"
	"github.com/ledor473/lightstep-api-go/pkg/v0.1/client/projects"
	"github.com/ledor473/lightstep-api-go/pkg/v0.1/client/services"
	"github.com/ledor473/lightstep-api-go/pkg/v0.1/client/snapshots"
	"github.com/ledor473/lightstep-api-go/pkg/v0.1/client/streams"
	"github.com/ledor473/lightstep-api-go/pkg/v0.1/client/test"
	"github.com/ledor473/lightstep-api-go/pkg/v0.1/client/traces"
	"github.com/ledor473/lightstep-api-go/pkg/v0.1/client/workflow_links"
)

// Default lightstep HTTP client.
var Default = NewHTTPClient(nil)

const (
	// DefaultHost is the default Host
	// found in Meta (info) section of spec file
	DefaultHost string = "api.lightstep.com"
	// DefaultBasePath is the default BasePath
	// found in Meta (info) section of spec file
	DefaultBasePath string = "/public/v0.1"
)

// DefaultSchemes are the default schemes found in Meta (info) section of spec file
var DefaultSchemes = []string{"http", "https"}

// NewHTTPClient creates a new lightstep HTTP client.
func NewHTTPClient(formats strfmt.Registry) *Lightstep {
	return NewHTTPClientWithConfig(formats, nil)
}

// NewHTTPClientWithConfig creates a new lightstep HTTP client,
// using a customizable transport config.
func NewHTTPClientWithConfig(formats strfmt.Registry, cfg *TransportConfig) *Lightstep {
	// ensure nullable parameters have default
	if cfg == nil {
		cfg = DefaultTransportConfig()
	}

	// create transport and client
	transport := httptransport.New(cfg.Host, cfg.BasePath, cfg.Schemes)
	return New(transport, formats)
}

// New creates a new lightstep client
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Lightstep {
	// ensure nullable parameters have default
	if formats == nil {
		formats = strfmt.Default
	}

	cli := new(Lightstep)
	cli.Transport = transport
	cli.Conditions = conditions.New(transport, formats)
	cli.Dashboards = dashboards.New(transport, formats)
	cli.Projects = projects.New(transport, formats)
	cli.Services = services.New(transport, formats)
	cli.Snapshots = snapshots.New(transport, formats)
	cli.Streams = streams.New(transport, formats)
	cli.Test = test.New(transport, formats)
	cli.Traces = traces.New(transport, formats)
	cli.WorkflowLinks = workflow_links.New(transport, formats)
	return cli
}

// DefaultTransportConfig creates a TransportConfig with the
// default settings taken from the meta section of the spec file.
func DefaultTransportConfig() *TransportConfig {
	return &TransportConfig{
		Host:     DefaultHost,
		BasePath: DefaultBasePath,
		Schemes:  DefaultSchemes,
	}
}

// TransportConfig contains the transport related info,
// found in the meta section of the spec file.
type TransportConfig struct {
	Host     string
	BasePath string
	Schemes  []string
}

// WithHost overrides the default host,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithHost(host string) *TransportConfig {
	cfg.Host = host
	return cfg
}

// WithBasePath overrides the default basePath,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithBasePath(basePath string) *TransportConfig {
	cfg.BasePath = basePath
	return cfg
}

// WithSchemes overrides the default schemes,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithSchemes(schemes []string) *TransportConfig {
	cfg.Schemes = schemes
	return cfg
}

// Lightstep is a client for lightstep
type Lightstep struct {
	Conditions conditions.ClientService

	Dashboards dashboards.ClientService

	Projects projects.ClientService

	Services services.ClientService

	Snapshots snapshots.ClientService

	Streams streams.ClientService

	Test test.ClientService

	Traces traces.ClientService

	WorkflowLinks workflow_links.ClientService

	Transport runtime.ClientTransport
}

// SetTransport changes the transport on the client and all its subresources
func (c *Lightstep) SetTransport(transport runtime.ClientTransport) {
	c.Transport = transport
	c.Conditions.SetTransport(transport)
	c.Dashboards.SetTransport(transport)
	c.Projects.SetTransport(transport)
	c.Services.SetTransport(transport)
	c.Snapshots.SetTransport(transport)
	c.Streams.SetTransport(transport)
	c.Test.SetTransport(transport)
	c.Traces.SetTransport(transport)
	c.WorkflowLinks.SetTransport(transport)
}
