// Code generated by go-swagger; DO NOT EDIT.

package test

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// TestReadReader is a Reader for the TestRead structure.
type TestReadReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *TestReadReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewTestReadOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewTestReadUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewTestReadOK creates a TestReadOK with default headers values
func NewTestReadOK() *TestReadOK {
	return &TestReadOK{}
}

/*TestReadOK handles this case with default header values.

OK!
*/
type TestReadOK struct {
	Payload interface{}
}

func (o *TestReadOK) Error() string {
	return fmt.Sprintf("[GET /{organization}/test][%d] testReadOK  %+v", 200, o.Payload)
}

func (o *TestReadOK) GetPayload() interface{} {
	return o.Payload
}

func (o *TestReadOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewTestReadUnauthorized creates a TestReadUnauthorized with default headers values
func NewTestReadUnauthorized() *TestReadUnauthorized {
	return &TestReadUnauthorized{}
}

/*TestReadUnauthorized handles this case with default header values.

Unauthorized
*/
type TestReadUnauthorized struct {
	Payload interface{}
}

func (o *TestReadUnauthorized) Error() string {
	return fmt.Sprintf("[GET /{organization}/test][%d] testReadUnauthorized  %+v", 401, o.Payload)
}

func (o *TestReadUnauthorized) GetPayload() interface{} {
	return o.Payload
}

func (o *TestReadUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
