// Code generated by go-swagger; DO NOT EDIT.

package test

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new test API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for test API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientService is the interface for Client methods
type ClientService interface {
	TestReadID(params *TestReadIDParams, authInfo runtime.ClientAuthInfoWriter) (*TestReadIDOK, error)

	TestWriteID(params *TestWriteIDParams, authInfo runtime.ClientAuthInfoWriter) (*TestWriteIDOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  TestReadID reads test

  A read-only endpoint for testing your authentication key
*/
func (a *Client) TestReadID(params *TestReadIDParams, authInfo runtime.ClientAuthInfoWriter) (*TestReadIDOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewTestReadIDParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "testReadID",
		Method:             "GET",
		PathPattern:        "/{organization}/test",
		ProducesMediaTypes: []string{"application/text"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &TestReadIDReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*TestReadIDOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for testReadID: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  TestWriteID writes test

  A write endpoint for testing your authentication key
*/
func (a *Client) TestWriteID(params *TestWriteIDParams, authInfo runtime.ClientAuthInfoWriter) (*TestWriteIDOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewTestWriteIDParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "testWriteID",
		Method:             "POST",
		PathPattern:        "/{organization}/test",
		ProducesMediaTypes: []string{"application/text"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &TestWriteIDReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*TestWriteIDOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for testWriteID: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
