// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ConditionRequestAttributes condition request attributes
//
// swagger:model conditionRequestAttributes
type ConditionRequestAttributes struct {

	// custom data
	CustomData map[string]interface{} `json:"custom-data,omitempty"`

	// evaluation window ms
	EvaluationWindowMs int64 `json:"eval-window-ms,omitempty"`

	// expression
	Expression string `json:"expression,omitempty"`

	// name
	Name string `json:"name,omitempty"`
}

// Validate validates this condition request attributes
func (m *ConditionRequestAttributes) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ConditionRequestAttributes) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ConditionRequestAttributes) UnmarshalBinary(b []byte) error {
	var res ConditionRequestAttributes
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
