// Code generated by go-swagger; DO NOT EDIT.

package streams

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteStreamIDParams creates a new DeleteStreamIDParams object
// with the default values initialized.
func NewDeleteStreamIDParams() *DeleteStreamIDParams {
	var ()
	return &DeleteStreamIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteStreamIDParamsWithTimeout creates a new DeleteStreamIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteStreamIDParamsWithTimeout(timeout time.Duration) *DeleteStreamIDParams {
	var ()
	return &DeleteStreamIDParams{

		timeout: timeout,
	}
}

// NewDeleteStreamIDParamsWithContext creates a new DeleteStreamIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteStreamIDParamsWithContext(ctx context.Context) *DeleteStreamIDParams {
	var ()
	return &DeleteStreamIDParams{

		Context: ctx,
	}
}

// NewDeleteStreamIDParamsWithHTTPClient creates a new DeleteStreamIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteStreamIDParamsWithHTTPClient(client *http.Client) *DeleteStreamIDParams {
	var ()
	return &DeleteStreamIDParams{
		HTTPClient: client,
	}
}

/*DeleteStreamIDParams contains all the parameters to send to the API endpoint
for the delete stream ID operation typically these are written to a http.Request
*/
type DeleteStreamIDParams struct {

	/*Organization
	  Name of the customer organization

	*/
	Organization string
	/*Project
	  Name of the customer project

	*/
	Project string
	/*StreamID
	  Identifier of the stream to delete

	*/
	StreamID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete stream ID params
func (o *DeleteStreamIDParams) WithTimeout(timeout time.Duration) *DeleteStreamIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete stream ID params
func (o *DeleteStreamIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete stream ID params
func (o *DeleteStreamIDParams) WithContext(ctx context.Context) *DeleteStreamIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete stream ID params
func (o *DeleteStreamIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete stream ID params
func (o *DeleteStreamIDParams) WithHTTPClient(client *http.Client) *DeleteStreamIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete stream ID params
func (o *DeleteStreamIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOrganization adds the organization to the delete stream ID params
func (o *DeleteStreamIDParams) WithOrganization(organization string) *DeleteStreamIDParams {
	o.SetOrganization(organization)
	return o
}

// SetOrganization adds the organization to the delete stream ID params
func (o *DeleteStreamIDParams) SetOrganization(organization string) {
	o.Organization = organization
}

// WithProject adds the project to the delete stream ID params
func (o *DeleteStreamIDParams) WithProject(project string) *DeleteStreamIDParams {
	o.SetProject(project)
	return o
}

// SetProject adds the project to the delete stream ID params
func (o *DeleteStreamIDParams) SetProject(project string) {
	o.Project = project
}

// WithStreamID adds the streamID to the delete stream ID params
func (o *DeleteStreamIDParams) WithStreamID(streamID string) *DeleteStreamIDParams {
	o.SetStreamID(streamID)
	return o
}

// SetStreamID adds the streamId to the delete stream ID params
func (o *DeleteStreamIDParams) SetStreamID(streamID string) {
	o.StreamID = streamID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteStreamIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param organization
	if err := r.SetPathParam("organization", o.Organization); err != nil {
		return err
	}

	// path param project
	if err := r.SetPathParam("project", o.Project); err != nil {
		return err
	}

	// path param stream-id
	if err := r.SetPathParam("stream-id", o.StreamID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
