// Code generated by go-swagger; DO NOT EDIT.

package streams

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/ledor473/lightstep-api-go/v0.2/models"
)

// NewPatchStreamIDParams creates a new PatchStreamIDParams object
// with the default values initialized.
func NewPatchStreamIDParams() *PatchStreamIDParams {
	var ()
	return &PatchStreamIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPatchStreamIDParamsWithTimeout creates a new PatchStreamIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPatchStreamIDParamsWithTimeout(timeout time.Duration) *PatchStreamIDParams {
	var ()
	return &PatchStreamIDParams{

		timeout: timeout,
	}
}

// NewPatchStreamIDParamsWithContext creates a new PatchStreamIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewPatchStreamIDParamsWithContext(ctx context.Context) *PatchStreamIDParams {
	var ()
	return &PatchStreamIDParams{

		Context: ctx,
	}
}

// NewPatchStreamIDParamsWithHTTPClient creates a new PatchStreamIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPatchStreamIDParamsWithHTTPClient(client *http.Client) *PatchStreamIDParams {
	var ()
	return &PatchStreamIDParams{
		HTTPClient: client,
	}
}

/*PatchStreamIDParams contains all the parameters to send to the API endpoint
for the patch stream ID operation typically these are written to a http.Request
*/
type PatchStreamIDParams struct {

	/*Data
	  Stream definition

	*/
	Data *models.CreateOrUpdateBody
	/*Organization
	  Name of the customer organization

	*/
	Organization string
	/*Project
	  Name of the customer project

	*/
	Project string
	/*StreamID
	  Identifier of the stream to modify

	*/
	StreamID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the patch stream ID params
func (o *PatchStreamIDParams) WithTimeout(timeout time.Duration) *PatchStreamIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the patch stream ID params
func (o *PatchStreamIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the patch stream ID params
func (o *PatchStreamIDParams) WithContext(ctx context.Context) *PatchStreamIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the patch stream ID params
func (o *PatchStreamIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the patch stream ID params
func (o *PatchStreamIDParams) WithHTTPClient(client *http.Client) *PatchStreamIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the patch stream ID params
func (o *PatchStreamIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the patch stream ID params
func (o *PatchStreamIDParams) WithData(data *models.CreateOrUpdateBody) *PatchStreamIDParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the patch stream ID params
func (o *PatchStreamIDParams) SetData(data *models.CreateOrUpdateBody) {
	o.Data = data
}

// WithOrganization adds the organization to the patch stream ID params
func (o *PatchStreamIDParams) WithOrganization(organization string) *PatchStreamIDParams {
	o.SetOrganization(organization)
	return o
}

// SetOrganization adds the organization to the patch stream ID params
func (o *PatchStreamIDParams) SetOrganization(organization string) {
	o.Organization = organization
}

// WithProject adds the project to the patch stream ID params
func (o *PatchStreamIDParams) WithProject(project string) *PatchStreamIDParams {
	o.SetProject(project)
	return o
}

// SetProject adds the project to the patch stream ID params
func (o *PatchStreamIDParams) SetProject(project string) {
	o.Project = project
}

// WithStreamID adds the streamID to the patch stream ID params
func (o *PatchStreamIDParams) WithStreamID(streamID string) *PatchStreamIDParams {
	o.SetStreamID(streamID)
	return o
}

// SetStreamID adds the streamId to the patch stream ID params
func (o *PatchStreamIDParams) SetStreamID(streamID string) {
	o.StreamID = streamID
}

// WriteToRequest writes these params to a swagger request
func (o *PatchStreamIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Data != nil {
		if err := r.SetBodyParam(o.Data); err != nil {
			return err
		}
	}

	// path param organization
	if err := r.SetPathParam("organization", o.Organization); err != nil {
		return err
	}

	// path param project
	if err := r.SetPathParam("project", o.Project); err != nil {
		return err
	}

	// path param stream-id
	if err := r.SetPathParam("stream-id", o.StreamID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
