// Code generated by go-swagger; DO NOT EDIT.

package streams

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/ledor473/lightstep-api-go/v0.2/models"
)

// NewPostStreamParams creates a new PostStreamParams object
// with the default values initialized.
func NewPostStreamParams() *PostStreamParams {
	var ()
	return &PostStreamParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostStreamParamsWithTimeout creates a new PostStreamParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostStreamParamsWithTimeout(timeout time.Duration) *PostStreamParams {
	var ()
	return &PostStreamParams{

		timeout: timeout,
	}
}

// NewPostStreamParamsWithContext creates a new PostStreamParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostStreamParamsWithContext(ctx context.Context) *PostStreamParams {
	var ()
	return &PostStreamParams{

		Context: ctx,
	}
}

// NewPostStreamParamsWithHTTPClient creates a new PostStreamParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostStreamParamsWithHTTPClient(client *http.Client) *PostStreamParams {
	var ()
	return &PostStreamParams{
		HTTPClient: client,
	}
}

/*PostStreamParams contains all the parameters to send to the API endpoint
for the post stream operation typically these are written to a http.Request
*/
type PostStreamParams struct {

	/*Data
	  Stream definition

	*/
	Data *models.CreateOrUpdateBody
	/*Organization
	  Name of the customer organization

	*/
	Organization string
	/*Project
	  Name of the customer project

	*/
	Project string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post stream params
func (o *PostStreamParams) WithTimeout(timeout time.Duration) *PostStreamParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post stream params
func (o *PostStreamParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post stream params
func (o *PostStreamParams) WithContext(ctx context.Context) *PostStreamParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post stream params
func (o *PostStreamParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post stream params
func (o *PostStreamParams) WithHTTPClient(client *http.Client) *PostStreamParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post stream params
func (o *PostStreamParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the post stream params
func (o *PostStreamParams) WithData(data *models.CreateOrUpdateBody) *PostStreamParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the post stream params
func (o *PostStreamParams) SetData(data *models.CreateOrUpdateBody) {
	o.Data = data
}

// WithOrganization adds the organization to the post stream params
func (o *PostStreamParams) WithOrganization(organization string) *PostStreamParams {
	o.SetOrganization(organization)
	return o
}

// SetOrganization adds the organization to the post stream params
func (o *PostStreamParams) SetOrganization(organization string) {
	o.Organization = organization
}

// WithProject adds the project to the post stream params
func (o *PostStreamParams) WithProject(project string) *PostStreamParams {
	o.SetProject(project)
	return o
}

// SetProject adds the project to the post stream params
func (o *PostStreamParams) SetProject(project string) {
	o.Project = project
}

// WriteToRequest writes these params to a swagger request
func (o *PostStreamParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Data != nil {
		if err := r.SetBodyParam(o.Data); err != nil {
			return err
		}
	}

	// path param organization
	if err := r.SetPathParam("organization", o.Organization); err != nil {
		return err
	}

	// path param project
	if err := r.SetPathParam("project", o.Project); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
