// Code generated by go-swagger; DO NOT EDIT.

package workflow_links

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// ListWorkflowLinksReader is a Reader for the ListWorkflowLinks structure.
type ListWorkflowLinksReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListWorkflowLinksReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListWorkflowLinksOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewListWorkflowLinksUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewListWorkflowLinksNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewListWorkflowLinksOK creates a ListWorkflowLinksOK with default headers values
func NewListWorkflowLinksOK() *ListWorkflowLinksOK {
	return &ListWorkflowLinksOK{}
}

/*ListWorkflowLinksOK handles this case with default header values.

JSON-formatted metadata about all workflow link definitions in the project
*/
type ListWorkflowLinksOK struct {
}

func (o *ListWorkflowLinksOK) Error() string {
	return fmt.Sprintf("[GET /{organization}/projects/{project}/wf_links][%d] listWorkflowLinksOK ", 200)
}

func (o *ListWorkflowLinksOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewListWorkflowLinksUnauthorized creates a ListWorkflowLinksUnauthorized with default headers values
func NewListWorkflowLinksUnauthorized() *ListWorkflowLinksUnauthorized {
	return &ListWorkflowLinksUnauthorized{}
}

/*ListWorkflowLinksUnauthorized handles this case with default header values.

The API Key does not provide access to this resource
*/
type ListWorkflowLinksUnauthorized struct {
}

func (o *ListWorkflowLinksUnauthorized) Error() string {
	return fmt.Sprintf("[GET /{organization}/projects/{project}/wf_links][%d] listWorkflowLinksUnauthorized ", 401)
}

func (o *ListWorkflowLinksUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewListWorkflowLinksNotFound creates a ListWorkflowLinksNotFound with default headers values
func NewListWorkflowLinksNotFound() *ListWorkflowLinksNotFound {
	return &ListWorkflowLinksNotFound{}
}

/*ListWorkflowLinksNotFound handles this case with default header values.

Organization or project not found
*/
type ListWorkflowLinksNotFound struct {
}

func (o *ListWorkflowLinksNotFound) Error() string {
	return fmt.Sprintf("[GET /{organization}/projects/{project}/wf_links][%d] listWorkflowLinksNotFound ", 404)
}

func (o *ListWorkflowLinksNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
