// Code generated by go-swagger; DO NOT EDIT.

package projects

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetProjectIDParams creates a new GetProjectIDParams object
// with the default values initialized.
func NewGetProjectIDParams() *GetProjectIDParams {
	var ()
	return &GetProjectIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetProjectIDParamsWithTimeout creates a new GetProjectIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetProjectIDParamsWithTimeout(timeout time.Duration) *GetProjectIDParams {
	var ()
	return &GetProjectIDParams{

		timeout: timeout,
	}
}

// NewGetProjectIDParamsWithContext creates a new GetProjectIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetProjectIDParamsWithContext(ctx context.Context) *GetProjectIDParams {
	var ()
	return &GetProjectIDParams{

		Context: ctx,
	}
}

// NewGetProjectIDParamsWithHTTPClient creates a new GetProjectIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetProjectIDParamsWithHTTPClient(client *http.Client) *GetProjectIDParams {
	var ()
	return &GetProjectIDParams{
		HTTPClient: client,
	}
}

/*GetProjectIDParams contains all the parameters to send to the API endpoint
for the get project ID operation typically these are written to a http.Request
*/
type GetProjectIDParams struct {

	/*Organization
	  Name of the customer organization

	*/
	Organization string
	/*Project
	  Name of the customer project

	*/
	Project string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get project ID params
func (o *GetProjectIDParams) WithTimeout(timeout time.Duration) *GetProjectIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get project ID params
func (o *GetProjectIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get project ID params
func (o *GetProjectIDParams) WithContext(ctx context.Context) *GetProjectIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get project ID params
func (o *GetProjectIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get project ID params
func (o *GetProjectIDParams) WithHTTPClient(client *http.Client) *GetProjectIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get project ID params
func (o *GetProjectIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOrganization adds the organization to the get project ID params
func (o *GetProjectIDParams) WithOrganization(organization string) *GetProjectIDParams {
	o.SetOrganization(organization)
	return o
}

// SetOrganization adds the organization to the get project ID params
func (o *GetProjectIDParams) SetOrganization(organization string) {
	o.Organization = organization
}

// WithProject adds the project to the get project ID params
func (o *GetProjectIDParams) WithProject(project string) *GetProjectIDParams {
	o.SetProject(project)
	return o
}

// SetProject adds the project to the get project ID params
func (o *GetProjectIDParams) SetProject(project string) {
	o.Project = project
}

// WriteToRequest writes these params to a swagger request
func (o *GetProjectIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param organization
	if err := r.SetPathParam("organization", o.Organization); err != nil {
		return err
	}

	// path param project
	if err := r.SetPathParam("project", o.Project); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
