// Code generated by go-swagger; DO NOT EDIT.

package snapshots

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/ledor473/lightstep-api-go/v0.1/models"
)

// NewCreateSnapshotParams creates a new CreateSnapshotParams object
// with the default values initialized.
func NewCreateSnapshotParams() *CreateSnapshotParams {
	var ()
	return &CreateSnapshotParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateSnapshotParamsWithTimeout creates a new CreateSnapshotParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateSnapshotParamsWithTimeout(timeout time.Duration) *CreateSnapshotParams {
	var ()
	return &CreateSnapshotParams{

		timeout: timeout,
	}
}

// NewCreateSnapshotParamsWithContext creates a new CreateSnapshotParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateSnapshotParamsWithContext(ctx context.Context) *CreateSnapshotParams {
	var ()
	return &CreateSnapshotParams{

		Context: ctx,
	}
}

// NewCreateSnapshotParamsWithHTTPClient creates a new CreateSnapshotParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateSnapshotParamsWithHTTPClient(client *http.Client) *CreateSnapshotParams {
	var ()
	return &CreateSnapshotParams{
		HTTPClient: client,
	}
}

/*CreateSnapshotParams contains all the parameters to send to the API endpoint
for the create snapshot operation typically these are written to a http.Request
*/
type CreateSnapshotParams struct {

	/*Data
	  Span query to create a snapshot for

	*/
	Data *models.SnapshotCreate
	/*Organization
	  Name of the customer organization

	*/
	Organization string
	/*Project
	  Name of the customer project

	*/
	Project string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create snapshot params
func (o *CreateSnapshotParams) WithTimeout(timeout time.Duration) *CreateSnapshotParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create snapshot params
func (o *CreateSnapshotParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create snapshot params
func (o *CreateSnapshotParams) WithContext(ctx context.Context) *CreateSnapshotParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create snapshot params
func (o *CreateSnapshotParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create snapshot params
func (o *CreateSnapshotParams) WithHTTPClient(client *http.Client) *CreateSnapshotParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create snapshot params
func (o *CreateSnapshotParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the create snapshot params
func (o *CreateSnapshotParams) WithData(data *models.SnapshotCreate) *CreateSnapshotParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the create snapshot params
func (o *CreateSnapshotParams) SetData(data *models.SnapshotCreate) {
	o.Data = data
}

// WithOrganization adds the organization to the create snapshot params
func (o *CreateSnapshotParams) WithOrganization(organization string) *CreateSnapshotParams {
	o.SetOrganization(organization)
	return o
}

// SetOrganization adds the organization to the create snapshot params
func (o *CreateSnapshotParams) SetOrganization(organization string) {
	o.Organization = organization
}

// WithProject adds the project to the create snapshot params
func (o *CreateSnapshotParams) WithProject(project string) *CreateSnapshotParams {
	o.SetProject(project)
	return o
}

// SetProject adds the project to the create snapshot params
func (o *CreateSnapshotParams) SetProject(project string) {
	o.Project = project
}

// WriteToRequest writes these params to a swagger request
func (o *CreateSnapshotParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Data != nil {
		if err := r.SetBodyParam(o.Data); err != nil {
			return err
		}
	}

	// path param organization
	if err := r.SetPathParam("organization", o.Organization); err != nil {
		return err
	}

	// path param project
	if err := r.SetPathParam("project", o.Project); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
