// Code generated by go-swagger; DO NOT EDIT.

package dashboards

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new dashboards API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for dashboards API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientService is the interface for Client methods
type ClientService interface {
	CreateDashboardID(params *CreateDashboardIDParams, authInfo runtime.ClientAuthInfoWriter) (*CreateDashboardIDOK, error)

	DeleteDashboardID(params *DeleteDashboardIDParams, authInfo runtime.ClientAuthInfoWriter) (*DeleteDashboardIDNoContent, error)

	GetDashboardID(params *GetDashboardIDParams, authInfo runtime.ClientAuthInfoWriter) (*GetDashboardIDOK, error)

	ListDashboardsID(params *ListDashboardsIDParams, authInfo runtime.ClientAuthInfoWriter) (*ListDashboardsIDOK, error)

	PatchDashboardID(params *PatchDashboardIDParams, authInfo runtime.ClientAuthInfoWriter) (*PatchDashboardIDOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  CreateDashboardID creates dashboard

  Creates a new dashboard, with inline stream definitions. Automatically creates the necessary streams if they do not already exist.
*/
func (a *Client) CreateDashboardID(params *CreateDashboardIDParams, authInfo runtime.ClientAuthInfoWriter) (*CreateDashboardIDOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewCreateDashboardIDParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "createDashboardID",
		Method:             "POST",
		PathPattern:        "/{organization}/projects/{project}/dashboards",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &CreateDashboardIDReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*CreateDashboardIDOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for createDashboardID: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  DeleteDashboardID deletes dashboard

  Deletes an existing dashboard. Deleting a dashboard only deletes the dashboard; the Streams are still available.
*/
func (a *Client) DeleteDashboardID(params *DeleteDashboardIDParams, authInfo runtime.ClientAuthInfoWriter) (*DeleteDashboardIDNoContent, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDeleteDashboardIDParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "deleteDashboardID",
		Method:             "DELETE",
		PathPattern:        "/{organization}/projects/{project}/dashboard/{dashboard-id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &DeleteDashboardIDReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*DeleteDashboardIDNoContent)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for deleteDashboardID: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  GetDashboardID gets dashboard

  Returns complete information about a specific dashboard, including stream definitions
*/
func (a *Client) GetDashboardID(params *GetDashboardIDParams, authInfo runtime.ClientAuthInfoWriter) (*GetDashboardIDOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetDashboardIDParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getDashboardID",
		Method:             "GET",
		PathPattern:        "/{organization}/projects/{project}/dashboards/{dashboard-id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &GetDashboardIDReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetDashboardIDOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for getDashboardID: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  ListDashboardsID lists dashboards

  Returns information about all dashboards in a project
*/
func (a *Client) ListDashboardsID(params *ListDashboardsIDParams, authInfo runtime.ClientAuthInfoWriter) (*ListDashboardsIDOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewListDashboardsIDParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "listDashboardsID",
		Method:             "GET",
		PathPattern:        "/{organization}/projects/{project}/dashboards",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &ListDashboardsIDReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ListDashboardsIDOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for listDashboardsID: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  PatchDashboardID updates dashboard

  Updates the dashboard with a new name (if applicable), and replaces the set of streams on the dashboard. Streams that are removed from the dashboard will not be deleted from the project. Streams that are not supplied are removed from the dashboard.
*/
func (a *Client) PatchDashboardID(params *PatchDashboardIDParams, authInfo runtime.ClientAuthInfoWriter) (*PatchDashboardIDOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPatchDashboardIDParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "patchDashboardID",
		Method:             "PATCH",
		PathPattern:        "/{organization}/projects/{project}/dashboards/{dashboard-id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &PatchDashboardIDReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*PatchDashboardIDOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for patchDashboardID: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
