// Code generated by go-swagger; DO NOT EDIT.

package dashboards

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteDashboardIDParams creates a new DeleteDashboardIDParams object
// with the default values initialized.
func NewDeleteDashboardIDParams() *DeleteDashboardIDParams {
	var ()
	return &DeleteDashboardIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteDashboardIDParamsWithTimeout creates a new DeleteDashboardIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteDashboardIDParamsWithTimeout(timeout time.Duration) *DeleteDashboardIDParams {
	var ()
	return &DeleteDashboardIDParams{

		timeout: timeout,
	}
}

// NewDeleteDashboardIDParamsWithContext creates a new DeleteDashboardIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteDashboardIDParamsWithContext(ctx context.Context) *DeleteDashboardIDParams {
	var ()
	return &DeleteDashboardIDParams{

		Context: ctx,
	}
}

// NewDeleteDashboardIDParamsWithHTTPClient creates a new DeleteDashboardIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteDashboardIDParamsWithHTTPClient(client *http.Client) *DeleteDashboardIDParams {
	var ()
	return &DeleteDashboardIDParams{
		HTTPClient: client,
	}
}

/*DeleteDashboardIDParams contains all the parameters to send to the API endpoint
for the delete dashboard ID operation typically these are written to a http.Request
*/
type DeleteDashboardIDParams struct {

	/*DashboardID
	  Identifier of the dashboard to delete

	*/
	DashboardID string
	/*Organization
	  Name of the customer organization

	*/
	Organization string
	/*Project
	  Name of the customer project

	*/
	Project string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete dashboard ID params
func (o *DeleteDashboardIDParams) WithTimeout(timeout time.Duration) *DeleteDashboardIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete dashboard ID params
func (o *DeleteDashboardIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete dashboard ID params
func (o *DeleteDashboardIDParams) WithContext(ctx context.Context) *DeleteDashboardIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete dashboard ID params
func (o *DeleteDashboardIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete dashboard ID params
func (o *DeleteDashboardIDParams) WithHTTPClient(client *http.Client) *DeleteDashboardIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete dashboard ID params
func (o *DeleteDashboardIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDashboardID adds the dashboardID to the delete dashboard ID params
func (o *DeleteDashboardIDParams) WithDashboardID(dashboardID string) *DeleteDashboardIDParams {
	o.SetDashboardID(dashboardID)
	return o
}

// SetDashboardID adds the dashboardId to the delete dashboard ID params
func (o *DeleteDashboardIDParams) SetDashboardID(dashboardID string) {
	o.DashboardID = dashboardID
}

// WithOrganization adds the organization to the delete dashboard ID params
func (o *DeleteDashboardIDParams) WithOrganization(organization string) *DeleteDashboardIDParams {
	o.SetOrganization(organization)
	return o
}

// SetOrganization adds the organization to the delete dashboard ID params
func (o *DeleteDashboardIDParams) SetOrganization(organization string) {
	o.Organization = organization
}

// WithProject adds the project to the delete dashboard ID params
func (o *DeleteDashboardIDParams) WithProject(project string) *DeleteDashboardIDParams {
	o.SetProject(project)
	return o
}

// SetProject adds the project to the delete dashboard ID params
func (o *DeleteDashboardIDParams) SetProject(project string) {
	o.Project = project
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteDashboardIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param dashboard-id
	if err := r.SetPathParam("dashboard-id", o.DashboardID); err != nil {
		return err
	}

	// path param organization
	if err := r.SetPathParam("organization", o.Organization); err != nil {
		return err
	}

	// path param project
	if err := r.SetPathParam("project", o.Project); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
