// Code generated by go-swagger; DO NOT EDIT.

package dashboards

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewListDashboardsIDParams creates a new ListDashboardsIDParams object
// with the default values initialized.
func NewListDashboardsIDParams() *ListDashboardsIDParams {
	var ()
	return &ListDashboardsIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewListDashboardsIDParamsWithTimeout creates a new ListDashboardsIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListDashboardsIDParamsWithTimeout(timeout time.Duration) *ListDashboardsIDParams {
	var ()
	return &ListDashboardsIDParams{

		timeout: timeout,
	}
}

// NewListDashboardsIDParamsWithContext creates a new ListDashboardsIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewListDashboardsIDParamsWithContext(ctx context.Context) *ListDashboardsIDParams {
	var ()
	return &ListDashboardsIDParams{

		Context: ctx,
	}
}

// NewListDashboardsIDParamsWithHTTPClient creates a new ListDashboardsIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewListDashboardsIDParamsWithHTTPClient(client *http.Client) *ListDashboardsIDParams {
	var ()
	return &ListDashboardsIDParams{
		HTTPClient: client,
	}
}

/*ListDashboardsIDParams contains all the parameters to send to the API endpoint
for the list dashboards ID operation typically these are written to a http.Request
*/
type ListDashboardsIDParams struct {

	/*Organization
	  Name of the customer organization

	*/
	Organization string
	/*Project
	  Name of the customer project

	*/
	Project string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list dashboards ID params
func (o *ListDashboardsIDParams) WithTimeout(timeout time.Duration) *ListDashboardsIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list dashboards ID params
func (o *ListDashboardsIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list dashboards ID params
func (o *ListDashboardsIDParams) WithContext(ctx context.Context) *ListDashboardsIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list dashboards ID params
func (o *ListDashboardsIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list dashboards ID params
func (o *ListDashboardsIDParams) WithHTTPClient(client *http.Client) *ListDashboardsIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list dashboards ID params
func (o *ListDashboardsIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOrganization adds the organization to the list dashboards ID params
func (o *ListDashboardsIDParams) WithOrganization(organization string) *ListDashboardsIDParams {
	o.SetOrganization(organization)
	return o
}

// SetOrganization adds the organization to the list dashboards ID params
func (o *ListDashboardsIDParams) SetOrganization(organization string) {
	o.Organization = organization
}

// WithProject adds the project to the list dashboards ID params
func (o *ListDashboardsIDParams) WithProject(project string) *ListDashboardsIDParams {
	o.SetProject(project)
	return o
}

// SetProject adds the project to the list dashboards ID params
func (o *ListDashboardsIDParams) SetProject(project string) {
	o.Project = project
}

// WriteToRequest writes these params to a swagger request
func (o *ListDashboardsIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param organization
	if err := r.SetPathParam("organization", o.Organization); err != nil {
		return err
	}

	// path param project
	if err := r.SetPathParam("project", o.Project); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
