// Code generated by go-swagger; DO NOT EDIT.

package client

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"net/url"

	"github.com/go-openapi/runtime"
	rtclient "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/ledor473/lightstep-api-go/pkg/v0.2/client/conditions"
	"github.com/ledor473/lightstep-api-go/pkg/v0.2/client/dashboards"
	"github.com/ledor473/lightstep-api-go/pkg/v0.2/client/projects"
	"github.com/ledor473/lightstep-api-go/pkg/v0.2/client/services"
	"github.com/ledor473/lightstep-api-go/pkg/v0.2/client/snapshots"
	"github.com/ledor473/lightstep-api-go/pkg/v0.2/client/streams"
	"github.com/ledor473/lightstep-api-go/pkg/v0.2/client/test"
	"github.com/ledor473/lightstep-api-go/pkg/v0.2/client/traces"
	"github.com/ledor473/lightstep-api-go/pkg/v0.2/client/workflow_links"
)

const (
	// DefaultHost is the default Host
	// found in Meta (info) section of spec file
	DefaultHost string = "api.lightstep.com"
	// DefaultBasePath is the default BasePath
	// found in Meta (info) section of spec file
	DefaultBasePath string = "/public/v0.2"
)

// DefaultSchemes are the default schemes found in Meta (info) section of spec file
var DefaultSchemes = []string{"http", "https"}

type Config struct {
	// URL is the base URL of the upstream server
	URL *url.URL
	// Transport is an inner transport for the client
	Transport http.RoundTripper
	// AuthInfo is for authentication
	AuthInfo runtime.ClientAuthInfoWriter
}

// New creates a new lightstep API HTTP client.
func New(c Config) *LightstepAPI {
	var (
		host     = DefaultHost
		basePath = DefaultBasePath
		schemes  = DefaultSchemes
	)

	if c.URL != nil {
		host = c.URL.Host
		basePath = c.URL.Path
		schemes = []string{c.URL.Scheme}
	}

	transport := rtclient.New(host, basePath, schemes)
	transport.Consumers["application/vnd.api+json"] = runtime.JSONConsumer()
	if c.Transport != nil {
		transport.Transport = c.Transport
	}

	cli := new(LightstepAPI)
	cli.Transport = transport
	cli.Conditions = conditions.New(transport, strfmt.Default, c.AuthInfo)
	cli.Dashboards = dashboards.New(transport, strfmt.Default, c.AuthInfo)
	cli.Projects = projects.New(transport, strfmt.Default, c.AuthInfo)
	cli.Services = services.New(transport, strfmt.Default, c.AuthInfo)
	cli.Snapshots = snapshots.New(transport, strfmt.Default, c.AuthInfo)
	cli.Streams = streams.New(transport, strfmt.Default, c.AuthInfo)
	cli.Test = test.New(transport, strfmt.Default, c.AuthInfo)
	cli.Traces = traces.New(transport, strfmt.Default, c.AuthInfo)
	cli.WorkflowLinks = workflow_links.New(transport, strfmt.Default, c.AuthInfo)
	return cli
}

// LightstepAPI is a client for lightstep API
type LightstepAPI struct {
	Conditions    *conditions.Client
	Dashboards    *dashboards.Client
	Projects      *projects.Client
	Services      *services.Client
	Snapshots     *snapshots.Client
	Streams       *streams.Client
	Test          *test.Client
	Traces        *traces.Client
	WorkflowLinks *workflow_links.Client
	Transport     runtime.ClientTransport
}
