// Code generated by go-swagger; DO NOT EDIT.

package dashboards

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetDashboardParams creates a new GetDashboardParams object
// with the default values initialized.
func NewGetDashboardParams() *GetDashboardParams {
	var ()
	return &GetDashboardParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetDashboardParamsWithTimeout creates a new GetDashboardParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetDashboardParamsWithTimeout(timeout time.Duration) *GetDashboardParams {
	var ()
	return &GetDashboardParams{

		timeout: timeout,
	}
}

// NewGetDashboardParamsWithContext creates a new GetDashboardParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetDashboardParamsWithContext(ctx context.Context) *GetDashboardParams {
	var ()
	return &GetDashboardParams{

		Context: ctx,
	}
}

// NewGetDashboardParamsWithHTTPClient creates a new GetDashboardParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetDashboardParamsWithHTTPClient(client *http.Client) *GetDashboardParams {
	var ()
	return &GetDashboardParams{
		HTTPClient: client,
	}
}

/*GetDashboardParams contains all the parameters to send to the API endpoint
for the get dashboard operation typically these are written to a http.Request
*/
type GetDashboardParams struct {

	/*DashboardID
	  Dashboard identifier

	*/
	DashboardID string
	/*Organization
	  Name of the customer organization

	*/
	Organization string
	/*Project
	  Name of the customer project

	*/
	Project string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get dashboard params
func (o *GetDashboardParams) WithTimeout(timeout time.Duration) *GetDashboardParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get dashboard params
func (o *GetDashboardParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get dashboard params
func (o *GetDashboardParams) WithContext(ctx context.Context) *GetDashboardParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get dashboard params
func (o *GetDashboardParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get dashboard params
func (o *GetDashboardParams) WithHTTPClient(client *http.Client) *GetDashboardParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get dashboard params
func (o *GetDashboardParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDashboardID adds the dashboardID to the get dashboard params
func (o *GetDashboardParams) WithDashboardID(dashboardID string) *GetDashboardParams {
	o.SetDashboardID(dashboardID)
	return o
}

// SetDashboardID adds the dashboardId to the get dashboard params
func (o *GetDashboardParams) SetDashboardID(dashboardID string) {
	o.DashboardID = dashboardID
}

// WithOrganization adds the organization to the get dashboard params
func (o *GetDashboardParams) WithOrganization(organization string) *GetDashboardParams {
	o.SetOrganization(organization)
	return o
}

// SetOrganization adds the organization to the get dashboard params
func (o *GetDashboardParams) SetOrganization(organization string) {
	o.Organization = organization
}

// WithProject adds the project to the get dashboard params
func (o *GetDashboardParams) WithProject(project string) *GetDashboardParams {
	o.SetProject(project)
	return o
}

// SetProject adds the project to the get dashboard params
func (o *GetDashboardParams) SetProject(project string) {
	o.Project = project
}

// WriteToRequest writes these params to a swagger request
func (o *GetDashboardParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param dashboard-id
	if err := r.SetPathParam("dashboard-id", o.DashboardID); err != nil {
		return err
	}

	// path param organization
	if err := r.SetPathParam("organization", o.Organization); err != nil {
		return err
	}

	// path param project
	if err := r.SetPathParam("project", o.Project); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
