// Code generated by go-swagger; DO NOT EDIT.

package dashboards

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewListDashboardsParams creates a new ListDashboardsParams object
// with the default values initialized.
func NewListDashboardsParams() *ListDashboardsParams {
	var ()
	return &ListDashboardsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewListDashboardsParamsWithTimeout creates a new ListDashboardsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListDashboardsParamsWithTimeout(timeout time.Duration) *ListDashboardsParams {
	var ()
	return &ListDashboardsParams{

		timeout: timeout,
	}
}

// NewListDashboardsParamsWithContext creates a new ListDashboardsParams object
// with the default values initialized, and the ability to set a context for a request
func NewListDashboardsParamsWithContext(ctx context.Context) *ListDashboardsParams {
	var ()
	return &ListDashboardsParams{

		Context: ctx,
	}
}

// NewListDashboardsParamsWithHTTPClient creates a new ListDashboardsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewListDashboardsParamsWithHTTPClient(client *http.Client) *ListDashboardsParams {
	var ()
	return &ListDashboardsParams{
		HTTPClient: client,
	}
}

/*ListDashboardsParams contains all the parameters to send to the API endpoint
for the list dashboards operation typically these are written to a http.Request
*/
type ListDashboardsParams struct {

	/*Organization
	  Name of the customer organization

	*/
	Organization string
	/*Project
	  Name of the customer project

	*/
	Project string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list dashboards params
func (o *ListDashboardsParams) WithTimeout(timeout time.Duration) *ListDashboardsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list dashboards params
func (o *ListDashboardsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list dashboards params
func (o *ListDashboardsParams) WithContext(ctx context.Context) *ListDashboardsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list dashboards params
func (o *ListDashboardsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list dashboards params
func (o *ListDashboardsParams) WithHTTPClient(client *http.Client) *ListDashboardsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list dashboards params
func (o *ListDashboardsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOrganization adds the organization to the list dashboards params
func (o *ListDashboardsParams) WithOrganization(organization string) *ListDashboardsParams {
	o.SetOrganization(organization)
	return o
}

// SetOrganization adds the organization to the list dashboards params
func (o *ListDashboardsParams) SetOrganization(organization string) {
	o.Organization = organization
}

// WithProject adds the project to the list dashboards params
func (o *ListDashboardsParams) WithProject(project string) *ListDashboardsParams {
	o.SetProject(project)
	return o
}

// SetProject adds the project to the list dashboards params
func (o *ListDashboardsParams) SetProject(project string) {
	o.Project = project
}

// WriteToRequest writes these params to a swagger request
func (o *ListDashboardsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param organization
	if err := r.SetPathParam("organization", o.Organization); err != nil {
		return err
	}

	// path param project
	if err := r.SetPathParam("project", o.Project); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
