// Code generated by go-swagger; DO NOT EDIT.

package streams

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewListStreamsIDParams creates a new ListStreamsIDParams object
// with the default values initialized.
func NewListStreamsIDParams() *ListStreamsIDParams {
	var ()
	return &ListStreamsIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewListStreamsIDParamsWithTimeout creates a new ListStreamsIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListStreamsIDParamsWithTimeout(timeout time.Duration) *ListStreamsIDParams {
	var ()
	return &ListStreamsIDParams{

		timeout: timeout,
	}
}

// NewListStreamsIDParamsWithContext creates a new ListStreamsIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewListStreamsIDParamsWithContext(ctx context.Context) *ListStreamsIDParams {
	var ()
	return &ListStreamsIDParams{

		Context: ctx,
	}
}

// NewListStreamsIDParamsWithHTTPClient creates a new ListStreamsIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewListStreamsIDParamsWithHTTPClient(client *http.Client) *ListStreamsIDParams {
	var ()
	return &ListStreamsIDParams{
		HTTPClient: client,
	}
}

/*ListStreamsIDParams contains all the parameters to send to the API endpoint
for the list streams ID operation typically these are written to a http.Request
*/
type ListStreamsIDParams struct {

	/*Organization
	  Name of the customer organization

	*/
	Organization string
	/*Project
	  Name of the customer project

	*/
	Project string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list streams ID params
func (o *ListStreamsIDParams) WithTimeout(timeout time.Duration) *ListStreamsIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list streams ID params
func (o *ListStreamsIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list streams ID params
func (o *ListStreamsIDParams) WithContext(ctx context.Context) *ListStreamsIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list streams ID params
func (o *ListStreamsIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list streams ID params
func (o *ListStreamsIDParams) WithHTTPClient(client *http.Client) *ListStreamsIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list streams ID params
func (o *ListStreamsIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOrganization adds the organization to the list streams ID params
func (o *ListStreamsIDParams) WithOrganization(organization string) *ListStreamsIDParams {
	o.SetOrganization(organization)
	return o
}

// SetOrganization adds the organization to the list streams ID params
func (o *ListStreamsIDParams) SetOrganization(organization string) {
	o.Organization = organization
}

// WithProject adds the project to the list streams ID params
func (o *ListStreamsIDParams) WithProject(project string) *ListStreamsIDParams {
	o.SetProject(project)
	return o
}

// SetProject adds the project to the list streams ID params
func (o *ListStreamsIDParams) SetProject(project string) {
	o.Project = project
}

// WriteToRequest writes these params to a swagger request
func (o *ListStreamsIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param organization
	if err := r.SetPathParam("organization", o.Organization); err != nil {
		return err
	}

	// path param project
	if err := r.SetPathParam("project", o.Project); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
