// Code generated by go-swagger; DO NOT EDIT.

package streams

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/ledor473/lightstep-api-go/v0.1/models"
)

// NewPostSearchIDParams creates a new PostSearchIDParams object
// with the default values initialized.
func NewPostSearchIDParams() *PostSearchIDParams {
	var ()
	return &PostSearchIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostSearchIDParamsWithTimeout creates a new PostSearchIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostSearchIDParamsWithTimeout(timeout time.Duration) *PostSearchIDParams {
	var ()
	return &PostSearchIDParams{

		timeout: timeout,
	}
}

// NewPostSearchIDParamsWithContext creates a new PostSearchIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostSearchIDParamsWithContext(ctx context.Context) *PostSearchIDParams {
	var ()
	return &PostSearchIDParams{

		Context: ctx,
	}
}

// NewPostSearchIDParamsWithHTTPClient creates a new PostSearchIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostSearchIDParamsWithHTTPClient(client *http.Client) *PostSearchIDParams {
	var ()
	return &PostSearchIDParams{
		HTTPClient: client,
	}
}

/*PostSearchIDParams contains all the parameters to send to the API endpoint
for the post search ID operation typically these are written to a http.Request
*/
type PostSearchIDParams struct {

	/*Data
	  Stream definition

	*/
	Data *models.CreateOrUpdateBody
	/*Organization
	  Name of the customer organization

	*/
	Organization string
	/*Project
	  Name of the customer project

	*/
	Project string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post search ID params
func (o *PostSearchIDParams) WithTimeout(timeout time.Duration) *PostSearchIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post search ID params
func (o *PostSearchIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post search ID params
func (o *PostSearchIDParams) WithContext(ctx context.Context) *PostSearchIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post search ID params
func (o *PostSearchIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post search ID params
func (o *PostSearchIDParams) WithHTTPClient(client *http.Client) *PostSearchIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post search ID params
func (o *PostSearchIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the post search ID params
func (o *PostSearchIDParams) WithData(data *models.CreateOrUpdateBody) *PostSearchIDParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the post search ID params
func (o *PostSearchIDParams) SetData(data *models.CreateOrUpdateBody) {
	o.Data = data
}

// WithOrganization adds the organization to the post search ID params
func (o *PostSearchIDParams) WithOrganization(organization string) *PostSearchIDParams {
	o.SetOrganization(organization)
	return o
}

// SetOrganization adds the organization to the post search ID params
func (o *PostSearchIDParams) SetOrganization(organization string) {
	o.Organization = organization
}

// WithProject adds the project to the post search ID params
func (o *PostSearchIDParams) WithProject(project string) *PostSearchIDParams {
	o.SetProject(project)
	return o
}

// SetProject adds the project to the post search ID params
func (o *PostSearchIDParams) SetProject(project string) {
	o.Project = project
}

// WriteToRequest writes these params to a swagger request
func (o *PostSearchIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Data != nil {
		if err := r.SetBodyParam(o.Data); err != nil {
			return err
		}
	}

	// path param organization
	if err := r.SetPathParam("organization", o.Organization); err != nil {
		return err
	}

	// path param project
	if err := r.SetPathParam("project", o.Project); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
