// Code generated by go-swagger; DO NOT EDIT.

package workflow_links

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewListWorkflowLinksParams creates a new ListWorkflowLinksParams object
// with the default values initialized.
func NewListWorkflowLinksParams() *ListWorkflowLinksParams {
	var ()
	return &ListWorkflowLinksParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewListWorkflowLinksParamsWithTimeout creates a new ListWorkflowLinksParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListWorkflowLinksParamsWithTimeout(timeout time.Duration) *ListWorkflowLinksParams {
	var ()
	return &ListWorkflowLinksParams{

		timeout: timeout,
	}
}

// NewListWorkflowLinksParamsWithContext creates a new ListWorkflowLinksParams object
// with the default values initialized, and the ability to set a context for a request
func NewListWorkflowLinksParamsWithContext(ctx context.Context) *ListWorkflowLinksParams {
	var ()
	return &ListWorkflowLinksParams{

		Context: ctx,
	}
}

// NewListWorkflowLinksParamsWithHTTPClient creates a new ListWorkflowLinksParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewListWorkflowLinksParamsWithHTTPClient(client *http.Client) *ListWorkflowLinksParams {
	var ()
	return &ListWorkflowLinksParams{
		HTTPClient: client,
	}
}

/*ListWorkflowLinksParams contains all the parameters to send to the API endpoint
for the list workflow links operation typically these are written to a http.Request
*/
type ListWorkflowLinksParams struct {

	/*Organization
	  Name of the customer organization

	*/
	Organization string
	/*Project
	  Name of the customer project

	*/
	Project string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list workflow links params
func (o *ListWorkflowLinksParams) WithTimeout(timeout time.Duration) *ListWorkflowLinksParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list workflow links params
func (o *ListWorkflowLinksParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list workflow links params
func (o *ListWorkflowLinksParams) WithContext(ctx context.Context) *ListWorkflowLinksParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list workflow links params
func (o *ListWorkflowLinksParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list workflow links params
func (o *ListWorkflowLinksParams) WithHTTPClient(client *http.Client) *ListWorkflowLinksParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list workflow links params
func (o *ListWorkflowLinksParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOrganization adds the organization to the list workflow links params
func (o *ListWorkflowLinksParams) WithOrganization(organization string) *ListWorkflowLinksParams {
	o.SetOrganization(organization)
	return o
}

// SetOrganization adds the organization to the list workflow links params
func (o *ListWorkflowLinksParams) SetOrganization(organization string) {
	o.Organization = organization
}

// WithProject adds the project to the list workflow links params
func (o *ListWorkflowLinksParams) WithProject(project string) *ListWorkflowLinksParams {
	o.SetProject(project)
	return o
}

// SetProject adds the project to the list workflow links params
func (o *ListWorkflowLinksParams) SetProject(project string) {
	o.Project = project
}

// WriteToRequest writes these params to a swagger request
func (o *ListWorkflowLinksParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param organization
	if err := r.SetPathParam("organization", o.Organization); err != nil {
		return err
	}

	// path param project
	if err := r.SetPathParam("project", o.Project); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
