// Code generated by go-swagger; DO NOT EDIT.

package streams

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetStreamParams creates a new GetStreamParams object
// with the default values initialized.
func NewGetStreamParams() *GetStreamParams {
	var ()
	return &GetStreamParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetStreamParamsWithTimeout creates a new GetStreamParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetStreamParamsWithTimeout(timeout time.Duration) *GetStreamParams {
	var ()
	return &GetStreamParams{

		timeout: timeout,
	}
}

// NewGetStreamParamsWithContext creates a new GetStreamParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetStreamParamsWithContext(ctx context.Context) *GetStreamParams {
	var ()
	return &GetStreamParams{

		Context: ctx,
	}
}

// NewGetStreamParamsWithHTTPClient creates a new GetStreamParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetStreamParamsWithHTTPClient(client *http.Client) *GetStreamParams {
	var ()
	return &GetStreamParams{
		HTTPClient: client,
	}
}

/*GetStreamParams contains all the parameters to send to the API endpoint
for the get stream operation typically these are written to a http.Request
*/
type GetStreamParams struct {

	/*Organization
	  Name of the customer organization

	*/
	Organization string
	/*Project
	  Name of the customer project

	*/
	Project string
	/*StreamID
	  Stream identifier

	*/
	StreamID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get stream params
func (o *GetStreamParams) WithTimeout(timeout time.Duration) *GetStreamParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get stream params
func (o *GetStreamParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get stream params
func (o *GetStreamParams) WithContext(ctx context.Context) *GetStreamParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get stream params
func (o *GetStreamParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get stream params
func (o *GetStreamParams) WithHTTPClient(client *http.Client) *GetStreamParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get stream params
func (o *GetStreamParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOrganization adds the organization to the get stream params
func (o *GetStreamParams) WithOrganization(organization string) *GetStreamParams {
	o.SetOrganization(organization)
	return o
}

// SetOrganization adds the organization to the get stream params
func (o *GetStreamParams) SetOrganization(organization string) {
	o.Organization = organization
}

// WithProject adds the project to the get stream params
func (o *GetStreamParams) WithProject(project string) *GetStreamParams {
	o.SetProject(project)
	return o
}

// SetProject adds the project to the get stream params
func (o *GetStreamParams) SetProject(project string) {
	o.Project = project
}

// WithStreamID adds the streamID to the get stream params
func (o *GetStreamParams) WithStreamID(streamID string) *GetStreamParams {
	o.SetStreamID(streamID)
	return o
}

// SetStreamID adds the streamId to the get stream params
func (o *GetStreamParams) SetStreamID(streamID string) {
	o.StreamID = streamID
}

// WriteToRequest writes these params to a swagger request
func (o *GetStreamParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param organization
	if err := r.SetPathParam("organization", o.Organization); err != nil {
		return err
	}

	// path param project
	if err := r.SetPathParam("project", o.Project); err != nil {
		return err
	}

	// path param stream-id
	if err := r.SetPathParam("stream-id", o.StreamID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
